# docker-compose.yml
services:
  db-postgres:
    image: postgres:15.3-alpine
    container_name: db-postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5441:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d



  api:
    build: ./backend
    container_name: api
    restart: always
    env_file:
      - .env
    depends_on:
      - db-postgres
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
      - ./initdb:/docker-entrypoint-initdb.d

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - api